version: '3.6'

services:
  redis:
    image: redis:alpine
    container_name: redis

  api:
    container_name: myBlog-dev-api
    build:
      context: .

    volumes:
      - ./api:/opt/node-ref-app/api
      - .:/opt/node-ref-app/
      - ./package.json:/usr/app/package.json
      - ./yarn.lock:/usr/app/yarn.lock

    environment:
      - NODE_ENV=development

    expose:
      - 5000

    depends_on:
      - redis
      - db
    command: yarn run server
    image: partha360/node-ref-impl_api

  webapp:
    container_name: myBlog-dev
    build:
      context: ./client

    volumes:
      - ./client:/usr/app
      - ./client/package.json:/usr/app/package.json
      - ./client/yarn.lock:/usr/app/yarn.lock

    environment:
      - PORT=3000
      - NODE_ENV=development
    ports:
      - 3000:3000

    links:
      - api
    depends_on:
      - api
    command: yarn start
    image: partha360/node-ref-impl_webapp

  db:
    container_name: myBlog-dev-db
    image: mvertes/alpine-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - /data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --bind_ip_all # --quiet
